name: simsrl
description: A private, mobile-first virtual wardrobe and outfit try-on app.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_secure_storage: ^10.3.1
  http: ^1.6.0
  image_picker: ^1.2.3
  path_provider: ^2.1.6
  share_plus: ^13.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
